export default {
    '502': '502 Bad Gateway',
    '404': '404 Not Found',
    '0': '成功',
    '1': '失败',
    'REQUEST_ERROR': '请求错误', //4001
    'METHOD_ERROR': '方法错误', //4002
    'PARAMETER_ERROR': '参数错误', //4003
    'VALIDATION_ERROR': '验证错误', //4004
    'TOKEN_ERROR': '令牌错误', //4005
    'INTERNAL_ERROR': '内部错误', //4000
    'SERVICE_BUSY': '服务繁忙', //4009
    'INFO_NULL': '信息不存在', //4010
    'SESSIONID_INVALID': '登录态失效', //4101
    'USERNAME_ERROR': '用户名错误', //4102
    'PASSWORD_ERROR': '密码错误', //4103
    'PASSWORD_UNSET': '密码未设置', //4106
    'ACCOUNT_NULL': '账号不存在', //4107
    'ACCOUNT_EXISTED': '账号已存在', //4108
    'ACCOUNT_BLOCKED': '账号被封禁', //4109
    'CHECKCODE_ERROR': '验证码错误',
    'NO_PERMISSION': '无权限访问', //4120
    'PRODUCT_ONLINE': '商品已是上线状态',
    'BRAND_INEXISTENCE': '品牌未上线',
    'COMPANY_NULL': '无子公司',
    'BANNERID_ERROR': '删除失败',
    'PRODUCT_MUST_ONLINE': '添加失败,请检查是否已添加',
    'COST_NULL': '商品无进货价格',
    'USER_NULL': '用户未注册',
    'MANAGER_EXISTED': '该店铺已有店长',
    'ACCOUNT_BOUND': '该账户已存在',
    'TIME_OUT': '仅能删除一天内添加的数据',
    'IS_KEEPER': '已存在此管理员',
    'IS_SALESMAN': '已为店长或店员',
    'PRODUCT_OFFLINE': '商品为下线状态',
    'ACTIVITY_OFFLINE': '活动为下线状态',
    'NOT_EDITING': '上线过的活动无法删除',
    'COUPON_ONLINE': '上线过的优惠券无法删除',
    'PRODUCT_EXISTED': '该商品已在首页模块中',
    'EXISTED': '该品牌或商品已有活动',
    'DELETE_ERROR': '删除失败,上线过的商品无法删除',
    'BARCODE_EXISTED': '条形码已存在',
    'MORE_THAN_YEAR': '活动时间不允许超过一年',
    'IS_DEFAULT': '默认价格商品无法下线',
    'COMMAND_NOT_EXISTED': '指令不存在',
    'TOTAL_LIMITED': '一天只能提交一次',
    'REQUEST_ERROR': '请求错误',
    'SCORE_NOT_ENOUGH': '积分不足',
    'STOCK_EMPTY': '此奖品已领完',
    'TODAY_EXCHANGED': '今天已兑换，请明天再来',
    'TODAY_SIGNED_IN': '今天已经签到过啦',
    "ACCOUNT_ACTIVATED": "此账号已经激活其他身份",
    "ACCOUNT_BLOCKED": "账户已被限制",
    "ACCOUNT_BOUND": "账户已被绑定",
    "ACCOUNT_CREATE_FAILED": "账户创建失败",
    "ACCOUNT_INFO_NULL": "找不到账户信息",
    "ACCOUNT_NULL": "找不到账户信息",
    "ACCOUNT_TYPE_ERROR": "此账号已经是其他店店长/店员",
    "ADDRESS_ERROR": "地址出错",
    "ADDRESS_INFO_NULL": "地址信息为空",
    "ALIPAY_ACCOUNT_BOUND": "该支付宝已绑定其他账号",
    "APPLYING": "你已有在申请中的售后",
    "BACK_ERROR": "身份证反面图片错误",
    "BIZTYPE_ERROR": "业务类型错误",
    "CALC_ERROR": "计算错误",
    "CHECKCODE_ERROR": "验证码错误",
    "CITY_ERROR": "城市不能为空",
    "CODE_ERROR": "授权码不能为空",
    "COMPANY_ERROR": "公司不能为空",
    "CONTENT_ERROR": "反馈内容不能为空",
    "COUNTY_ERROR": "区/县不能为空",
    "COUPON_CAUGHT": "已经领过优惠券了",
    "COUPON_ERROR": "优惠券已被使用",
    "COUPON_EXPIRED": "优惠券已经过期",
    "DISCOUNT_USED_ERROR": "优惠码使用失败",
    "EXPRESSID_ERROR": "快递单号错误",
    "EXPRESSID_EXIST": "快递单号已存在",
    "FACEIMG_NOT_NULL": "手持身份证图片不能为空",
    "FACE_ERROR": "身份证正面图片错误",
    "FACE_IDCARDNO_ERROR": "身份证号码错误",
    "FACE_REALNAME_ERROR": "身份证姓名错误",
    "FREE_VALUE_ERROR": "金额超过上限",
    "GUARANTEE_ERROR": "担保方式不能为空",
    "IDCARDBACK_NOT_NULL": "身份证反面照不能为空",
    "IDCARDFRONT_NOT_NULL": "身份证正面照不能为空",
    "IDCARDNO_ERROR": "身份证号码验证失败",
    "IDCARDNO_NOT_NULL": "身份证号码不能为空",
    "IMAGE_BACK_ERROR": "身份证反面照片验证失败",
    "IMAGE_FACE_ERROR": "身份证正面照片验证失败",
    "IMAGE_PARSE_ERROR": "图片解析失败,\n请确认图片是否清晰正确",
    "IMEI_ERROR": "IMEI错误",
    "INFO_NULL": "用户信息为空",
    "INFO_SYNC_ERROR": "已通过实名,不能修改身份证信息",
    "INSERT_ERROR": "新增信息错误",
    "INSERT_ITEM_ERROR": "商品条形码已存在",
    "INTERNAL_ERROR": "服务器内部出错",
    "ITEM_EXISTED": "实物IMEI已存在",
    "ITEM_NOT_EXISTED": "实物信息不存在,请检查库存编号和IMEI",
    "ITEM_OUT_ERROR": "实物出库失败",
    "KEEPER_ERROR": "管理员信息错误",
    "KEEPER_NULL": "仓库不存在",
    "KEEPRER_NULL": "找不到仓库管理员",
    "LINKMAN_NOT_NULL": "联系人不能为空",
    "LINKTEL_ERROR": "联系人电话格式错误",
    "LINKTEL_NOT_NULL": "联系人电话不能为空",
    "MANAGER_EXISTED": "该店铺已有店长",
    "MANAGER_NULL": "管理员信息为空",
    "MAX_FREE_VALUE": "优惠超过上限,请重新设置优惠码",
    "METHOD_ERROR": "http请求方式出错",
    "MONTHS_ERROR": "租期不能为空",
    "MSGCODE_ERROR": "短信验证码错误",
    "MSGCODE_FAILED": "验证码发送失败",
    "MSGCODE_LIMIT": "今日发送次数已用完",
    "MSGCODE_UNUSED": "请等待短信验证码",
    "NOT_REGISTER": "该账号还没注册",
    "NO_MANAGER": "该店铺还没激活的店长",
    "NO_PERMISSION": "没有权限访问",
    "OAUTH_ACCESS_TOKEN_FAILED": "获取支付宝TOKEN失败",
    "OAUTH_CREATE_ERROR": "创建支付宝用户失败",
    "OAUTH_INFO_NULL": "找不到支付宝用户信息",
    "OAUTH_QUERY_ERROR": "获取支付宝用户信息失败",
    "OAUTH_UPDATE_ERROR": "更新支付宝用户信息失败",
    "OCR_ERROR": "图片解析失败,\n请确认图片是否清晰正确",
    "ORDERID_ERROR": "错误的订单ID",
    "ORDER_AUTH_DONE": "订单状态错误",
    "ORDER_COST_INSERT_ERROR": "新增计算结果错误",
    "ORDER_DELIVERY_DONE": "订单已经发货成功",
    "ORDER_ERROR": "没权限查看该订单",
    "ORDER_ITEM_FETCHED": "订单已经添加实物信息",
    "ORDER_NO_ITEM": "订单未添加实物信息",
    "ORDER_NULL": "找不到订单信息",
    "ORDER_STATUS_ERROR": "订单状态错误,请刷新",
    "OVERTIME": "已超时,不能取消订单了哦",
    "PARAMETER_LACKED": "缺少参数",
    "PICKTYPE_ERROR": "取货方式不能为空",
    "PLACE_ERROR": "详细地址不能为空",
    "POLICY_APPLAY_ERRPR": "申请保险失败",
    "POLICY_STATUS_ERROR": "保单已失效",
    "POSITION_ERROR": "职位不能为空",
    "PRICEID_ERROR": "错误的商品价格信息",
    "PRICE_NULL": "找不到商品价格信息",
    "PROCTDUCT_STOCK_ITEM_NULL": "没有找到商品实物信息",
    "PRODUCTID_ERROR": "商品不能为空",
    "PRODUCT_NULL": "商品已下架",
    "PRODUCT_OFFLINE": "商品已经下线",
    "PROVINCE_ERROR": "省份不能为空",
    "QRCODE_ERROR": "二维码类型错误",
    "REALNAME_ERROR": "真实名字验证失败",
    "REALNAME_NOT_NULL": "真实姓名不能为空",
    "REMARK_ERROR": "备注不能为空",
    "REPAIR_APPLYING": "此订单正在申请保险理赔",
    "REPAYMENT_ERROR": "还款方式不能为空",
    "REQUEST_ERROR": "服务器请求接口出错",
    "RETURNS_APPLYING": "此订单正在申请退换货",
    "SALESMANID_ERROR": "",
    "SALESMANTYPE_ERROR": "只有店长身份才能操作",
    "SALESMAN_ACTIVATED": "该店员已经激活",
    "SALESMAN_ERROR": "销售员信息错误",
    "SALESMAN_EXISTED": "该店员已经存在",
    "SALESMAN_NULL": "找不到销售员信息",
    "SALESMAN_STATUS_ERROR": "销售员已经被删除",
    "SCHOOL_ERROR": "学校不能为空",
    "SESSIONID_INVALID": "登录已失效",
    "SHOPID_ERROR": "找不到店铺",
    "SHOP_ERROR": "店铺错误",
    "SHOP_NULL": "店铺不存在",
    "SHOP_OPENED": "上线状态不能修改信息(店长除外)\n请先停用店铺",
    "STATUS_ERROR": "订单状态错误",
    "STORE_NULL": "找不到仓库",
    "SURPLUSRATIO_CALC_ERROR": "优惠码已失效,请重扫二维码",
    "TEL_ERROR": "手机号码错误",
    "TOKEN_ERROR": "TOKEN错误",
    "TOKEN_EXPIRED": "TOKEN已经失效，请重新扫码",
    "TOTAL_AUTH_DONE_LIMITED": "你已租太多单啦",
    "TOTAL_AUTH_WAIT_LIMITED": "你下太多单啦",
    "TOTAL_LIMITED": "已经反馈过了哦,请明天再来",
    "TOWN_ERROR": "乡镇不能为空",
    "TYPE_ERROR": "类型错误",
    "UNAUTHORIZED": "请先实名认证",
    "UNKNOWN": "操作失败",
    "UPDATE_ERROR": "更新信息错误",
    "USERNAME_BOUND": "该账户已绑定其他账号",
    "USERNAME_ERROR": "手机号码错误",
    "VALIDATION_ERROR": "请求参数错误",
    "WEIXIN_ACCOUNT_BOUND": "该微信已绑定其他账号",
    "WITHDRAW_CYCLE": "提现次数太频繁，7天可提现一次",
    "WITHDRAW_WAIT": "上次提现申请还在处理中",
    "YEAR_ERROR": "入学年份不能为空"
}